name: Deploy 'onboarding.near' Components to Mainnet

on:
  push:
    branches: [main]

jobs:
  deploy-mainnet:
    uses: nearbuilders/bos-workspace/.github/workflows/deploy.yml@main
    with:
      bw-legacy: false
      deploy-env: "mainnet"
      app-name: "onboarding.near"
      deploy-account-address: "onboarding.near"
      signer-account-address: "onboarding.near"
      signer-public-key: ${{ vars.BOS_SIGNER_PUBLIC_KEY }}
    secrets: 
      SIGNER_PRIVATE_KEY: ${{ secrets.BOS_SIGNER_PRIVATE_KEY }}
